name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

  deploy:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a multi-line script
      run: |
        apk add rsync openssh-client
        eval $(ssh-agent -s)
        echo ${{ SSH_MASTER_KEY }} | tr -d '\r' | ssh-add - > /dev/null
    - name: Deploy with Rsync
      run: rsync --itemize-changes --compress --verbose --archive --delete-before --update --exclude={"$DEPLOY_EXCLUDE"} --chown=$DEPLOY_CHOWN --chmod=Du=rwx,Dgo=rx,Fu=rw,Fgo=r --rsync-path="sudo rsync" --rsh "ssh -p $PROD_SSH_PORT -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" "$DEPLOY_BINARY" "web" "$PROD_SSH_USER"@"$PROD_SSH_HOST":"$PROD_DEPLOY_PATH"
