name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      run: |
        wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
    - name: Building binaries
      run: |
        ls
        dotnet restore
        dotnet build

  deploy:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup SSH
      run: |
        eval $(ssh-agent -s)
        echo ${{ secrets.SSH_MASTER_KEY }} | tr -d '\r' | ssh-add - > /dev/null
    - name: Deploy with Rsync
      run: rsync --itemize-changes --compress --verbose --archive --delete-before --update --exclude= --chown=www-josef:www-josef --chmod=Du=rwx,Dgo=rx,Fu=rw,Fgo=r --rsync-path="sudo rsync" --rsh "ssh -p 222 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" * sshztude@ztude.com:/www/website/josef
